# Generated by Django 4.2.7 on 2024-06-04 20:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="employee/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
