# Generated by Django 4.2.7 on 2024-06-04 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="author", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="posts",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="category", to="blog.category"
            ),
        ),
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="blog.tags"),
        ),
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post", to="blog.posts"),
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
