# Generated by Django 4.2.7 on 2024-05-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_posts_watched_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="author",
            field=models.ForeignKey(
                default=users.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
