# Generated by Django 4.2.7 on 2024-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_posts_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="is_recomendation",
            field=models.BooleanField(default=False),
        ),
    ]
